sudo: true
language: node_js
node_js:
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'

install:
  - npm install -g npm@latest
  - npm install
  - npm run bootstrap:ci

script:
  - npm run lint
  - npm run test
  - npm run build
  - if [[ $(git tag -l --contains HEAD | wc -c) -ne 0 ]]; then npm run do-publish; fi


after_success:
  - npm run codecov

notifications:
  email: false
